version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker
    links:
      - postgres
    ports:
      - 9292:9292
    # If you remove nginx, enable the following
    #ports:
    #  - "80:80"
    environment:
      DISPOSABLE_PSQL: "true"
      PACT_BROKER_DATABASE_ADAPTER : postgres
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: postgres
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_PORT: 5432
      PACT_BROKER_DATABASE_NAME: postgres

  # Nginx is not necessary, but demonstrates how
  # one might use a reverse proxy in front of the broker,
  # and includes the use of a self-signed TLS certificate
  nginx:
    image: nginx:alpine
    links:
      - broker_app:broker
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx:/etc/nginx/ssl
    ports:
      - "8443:443"
      - "80:80"